import {
  AccessoriesColor,
  AvatarColor,
  BackgroundColor,
  ClothesColor,
  EyesColor,
  HairColor,
  MouthColor,
  SkinColor,
} from './avatar-colors.js';

export const colorsMap: { [key in AvatarColor]: string } = {
  [SkinColor.Light]: '#E9C8BC',
  [SkinColor.Medium]: '#D69D70',
  [SkinColor.Dark]: '#88583B',
  [HairColor.Blond]: '#DEBE99',
  [HairColor.Brown]: '#4F1A00',
  [HairColor.Dark]: '#241C11',
  [HairColor.Red]: '#9A3300',
  [HairColor.Grey]: '#CABEAF',
  [EyesColor.Brown]: '#4E2031',
  [EyesColor.Blue]: '#0190BA',
  [EyesColor.Green]: '#91A567',
  [MouthColor.Pink]: '#FC96E7',
  [MouthColor.Coral]: '#FF7373',
  [MouthColor.Red]: '#C51010',
  [ClothesColor.Red]: '#FF0000',
  [ClothesColor.Blue]: '#0000FF',
  [ClothesColor.Black]: '#000000',
  [ClothesColor.White]: '#FFFFFF',
  [AccessoriesColor.Gold]: '#FFD700',
  [AccessoriesColor.Silver]: '#C0C0C0',
  [BackgroundColor.White]: '#FFFFFF',
  [BackgroundColor.Blue]: '#0000FF',
};
